In [0]:
import random
print("number guessing as a game")

###this variable is tracking chances 
chance=0
number=random.randint(1,9)
print("please guess a number from 1 to 9")

while chance<5:
  guess=int(input("enter a number"))

  if guess==number:
    print("congrats u won!!")
    break

  elif guess<number:
    print("your guess is bit low")

  else:
    print("its high") 

  chance+=1

  if not chance<5:
    print("ypu lost as the betting number is",number)

number guessing as a game
please guess a number from 1 to 9
enter a number5
your guess is bit low
enter a number8
its high
enter a number7
congrats u won!!


In [0]:
import numpy as np

In [0]:
mylist=[1,2,3]
np.array(mylist)

array([1, 2, 3])

In [0]:
mymetrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mymetrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [0]:
###for 0's
np.zeros(3)

array([0., 0., 0.])

In [0]:
###for 5*5 array
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
np.ones(3)

array([1., 1., 1.])

In [0]:
###for ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
###imp api's used to divide a matrix
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [0]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [0]:
###for identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
###for normal distrubution
np.random.rand(2)

array([0.93582492, 0.41490701])

In [0]:
np.random.rand(5,5)

array([[0.42489884, 0.52480973, 0.76699006, 0.40855129, 0.7388317 ],
       [0.87439549, 0.69012034, 0.96137979, 0.82551399, 0.93489357],
       [0.73465941, 0.70902794, 0.10115336, 0.85616363, 0.26527313],
       [0.0463179 , 0.41600769, 0.78751569, 0.85059773, 0.31235171],
       [0.09356116, 0.2470193 , 0.49795721, 0.73785259, 0.33510702]])

In [0]:
###for negetive
np.random.randn(5,5)

array([[-0.72387896, -0.45988703,  0.21438818,  0.73980981,  0.16375124],
       [ 0.13665987,  0.30807852, -0.67453054,  1.18231543, -0.97959911],
       [ 0.83238225, -0.05353284,  0.05109302,  1.49044416,  0.10879484],
       [-0.08307551,  0.48961403,  0.30941871,  1.63538434,  0.53638875],
       [-1.16895252, -0.99360236, -0.66688931,  0.0923248 ,  1.6810073 ]])

In [0]:
###for integers
np.random.randint(5)

4

In [0]:
np.random.randint(1,100,10)

array([28, 43, 68, 62, 13, 39, 96, 47, 32, 85])

In [0]:
arr=np.arange(25)

In [0]:
ranarr=np.random.randint(0,50,10)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr

array([18, 40, 41,  3,  2,  4,  4, 22,  5, 37])

In [0]:
###reshape into 2*2
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
ranarr

array([18, 40, 41,  3,  2,  4,  4, 22,  5, 37])

In [0]:
###to find max value in array
ranarr.max()

41

In [0]:
###to find max index
ranarr.argmax()

2

In [0]:
###to find min value
ranarr.min()

2

In [0]:
###to find min index
ranarr.argmin()

4

In [0]:
arr.shape

(25,)

In [0]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [0]:
###gives boundry value
arr.reshape(1,25).shape

(1, 25)

In [0]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [0]:
import numpy as np
arr=np.arange(0,10)

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
###adding two matrix
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
###mul of matrix
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
###sice 0/0 is not defined it gives is nan
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [0]:
###calculating power
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [0]:
np.max(arr)

9

In [0]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [0]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [0]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[7]

7

In [0]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[0:5]=100

In [0]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [0]:
slicearr=arr[0:6]

In [0]:
slicearr

array([100, 100, 100, 100, 100,   5])

In [0]:
slicearr[:]=99  ###to make all values as 99 (:) isused

In [0]:
slicearr

array([99, 99, 99, 99, 99, 99])

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [0]:
arrcopy=arr.copy()
arrcopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [0]:
arr2d=np.array(([5,10,15],[20,25,30],[35,40,45]))

In [0]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [0]:
arr2d[1]

array([20, 25, 30])

In [0]:
arr2d[1][2]

30

In [0]:
arr2d[:2][1:]

array([[20, 25, 30]])

In [0]:
arr2d[2]

array([35, 40, 45])

In [0]:
import numpy as np
arr2d=np.zeros((10,10))
arlength=arr2d.shape[1]
for i in range(arlength):
 arr2d[i]=i

In [0]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [0]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [0]:
arr2d[[6,4,2,5]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [0]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
boolarr=arr>4

In [0]:
arr[boolarr]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
from numpy import arange
from timeit import Timer

Nelements=10000
Ntimeits=10000

x=arange(Nelements)
y=range(Nelements)

tnumpy=Timer("x.sum()", "from __main__ import x")
tlist=Timer("sum(y)", "from __main__ import y")
print("numpy: %.3e" %(tnumpy.timeit(Ntimeits)/Ntimeits,))
print("list: %.3e" %(tlist.timeit(Ntimeits)/Ntimeits,))

numpy: 9.907e-06
list: 1.766e-04
